### ISSUE TITLE
Mi legyen a keretrendszer?

### ISSUE THREAD

**Issue by borazslo** [borazslo/koordinaltgyujtes#1]
- Én PHP-MySQL világban vagyok jártas, de egyébként lehet más alapokon is.
- Laravelt használtam már, de nem túl komplex nekünk? Talán pont hogy nem.
- Fontos, hogy aztán jól verzió követhető legyen
- Biztos nem WP, Joomla, meg ilyenek, mert fontos a nagyon egyszerű felület a felhasználóknak is.

**Comment by zgtamas** [comment]
PHP-nál én symfony-t, használtam már, de amúgy annyira nem vagyok otthon benne. NodeJS? nagyon elvetemült? :)

**Comment by edeak** [comment]
Javaslat:
- aws
- kotlin backend (abban vagyok gyors)
- rest api / graphql (a specifikaciot meg nem olvastam...)
- frontendrol nem tudok nyilatkozni

**Comment by fehergeri13** [comment]
Én frontenden react-ra szavazok (+tailwindcss), szerintem nagyon egyszerű, de lehet vue is. Angular pls ne. Szerintem egy firebase backend nagyon nagy segítség lehet, kb csak a frontendre kell fókuszálni. 

Backend oldalon én nodejs és koa-ban vagyok jártas. szerintem ne használjunk graphql-t. A REST API sokkal szélesebben supportalt, és szerintem simán elég

**Comment by progcode** [comment]
laravel + tailwind/bootstrap. 

@edeak @fehergeri13 

olyan javaslatokat szerintem felesleges adni, amirol valaki nem tudja, hogy pontosan mire jo ("(a specifikaciot meg nem olvastam...") es ne tegyunk felelotlen kijelenteseket, hogy "szerintem nagyon egyszerű."

Alapvetoen a pontos igenyt kell meghatarozni, utana lehet eldonteni, hogy az igenynek megfeleloen mi a legjobb stack, amihez a legtobben ertenek, es viszonylag gyorsan lehet benne fejleszteni. Teljesen felesleges verebre agyuval tuzelni is a projekt jelenlegi statuszaban (backend node, koa, graphql, firebase). @borazslo

**Comment by briff** [comment]
Én mérlegelnék low-code megoldást. Nekem mendix-szel van tapasztalatom, egy ilyen app pár nap alatt összerakható benne.

**Comment by molnarm** [comment]
Ha kimondottan a mostani ukrán helyzet kapcsán van szükség sürgősen valamire, akkor lehet, hogy valami low/no code cucc lenne a legjobb, biztos van valami ilyen egyszerű adatbázis-menedzselős dolog, de én nem ismerem őket.

Ha hosszabb távon van rá szükség, és mellékesen most is jó lenne, akkor van értelme nekiállni a fejlesztésnek. Sok platformot írtatok már, én bedobnám még a Djangót, mert király az automatikusan generált admin felülete (alapból se rossz és pár sor kóddal testre szabható).

**Comment by borazslo** [comment]
A sürgős változat áll fenn. Persze ha ma véget is érnének a harcok akkor is még hónapokig szükség lesz itt-ott ilyen olyan segítségre. De most van hogy nagyon gyorsan változik, hogy valahol teli van a raktár, másutt meg nagy a hiány. És mindig másból.

Vagyis jó minden low code és féli kész termék. Viszont az fontos, hogy a felhasználóknak (látogatóknak és gyűjtőhely fenntartóknak egyaránt)  nagyon egyszerű legyen a felület és használhatóság, hogy tényleg használják. És aztán tudjuk bővíteni. 

@progcode : az igényt megpróbáltam megfogalmazni a pár wireframe rajzon, az adatstruktúra vázlatban, és az extra fícsörök issue-kban. Szerintem sem feltétlen kell ehhez nagy ágyú. Csak hát nekem csupán rozsdás késem van. :D Számítok rátok.

**Comment by Saboteur777** [comment]
Sziasztok! 

Nem low-code, nem WordPress, de nem is Laravel: [Craft CMS](https://craftcms.com/).
Admin felületen összekattintgatható bejegyzés típusok, mezőkkel, GraphQl endpoint, Twig templating. A konfig változásokat egy yml fájlban tárolja, így a lokálban végzett változások "átmennek" productionbe, különösebb varázslás nélkül. 

Jó jogosultságkezelése van, így amíg nem készül frontendre egy admin felület a nem-admin usereknek, addig lehet hozzáférést adni a fő adminhoz.

**Comment by VFiber** [comment]
Sziasztok,
jönnék segíteni de eléggé elcsöndesült a repó.

Ha PHP/Mysql megközelítést szeretnétek, REST Api-val, akkor [API-Platform](https://api-platform.com) működhet, Symfony alapú elég okosan felépített rendszer, accept-typeokra építő response sémával (ha FE megmondja mit kér, a BE úgy válaszol, csakúgy mint Spring-ben).

Kotllin szintén működhet, abban aktívan nem tudok segíteni.

FE-ben (bocs, Angular) egy elég hasonló koncepciót elkezdtem, annyi eltéréssel, hogy egy offline PWA-t + Dexie-t (IndexedDB a kliensen) a kezdetektől beépíteni, hogy "telepítés" után akár a menekülteknek is lehessen használni hol van számukra segítség, ha van hozzáférésük nethez pedig tudná szinkronizálni magát az app, ennek kidolgozásába még bele sem kezdtem.

Ezt ha rendes REST Apira építjük, elindulhatunk akár két külön szálon is, az egyik csapat csinálja a desktop / user weboldalt a másik pedig a PWA alkalmazás irányt amit on-site lehetne használni akár "telepített" alkalmazásként is adminként.

REST Api + Auth server (Auth0 / API-platform & lexik jwt bundle?) + Fe megközelítésben akár Angular akár PHP akár ezek üzemeltetési konfigjában is tudnék aktívan segíteni (Mysltől Nginx/Apacheig).

**Comment by borazslo** [comment]
Köszi @VFiber , hogy jönnél. Az élet most (még éppen) leginkább a slack-en van. Gyere, nézz be: https://join.slack.com/t/jladnij/shared_invite/zt-14o2v6u1d-E3XUeqiP3IZAmPFIgxLqvw
Azért indult két másik repo is a backend-nek és frontendnek és egy miro boardon mindenféle alakuló fícsörök, wireframe, kategóriák, stb. Szóval azért van élet. De ha teszel hozzá még jobb.

Még izgalmasabb lehet számodra, hogy egy másik csapatnak van egy slack oldala ahol arról beszélgetnek, hogy hogyan lehetne egy olyan közös API-t, sőt talán RFC-t. Ha nem is áll még úgy hogy most lehet alkalmazkodni ahhoz, de mindenképp izgalmas követni a folyamatot. Ha adsz emailt, akkor meghívatlak oda (is).

**Comment by borazslo** [comment]
Közben a slack-en kialakult:
- backend: django - https://github.com/joladnijo/joladnijo-backend
- frontend: react - https://github.com/joladnijo/joladnijo-webapp

Persze nem biztos, hogy ez a legtökéletesebb stack, de az összeállít teamben ez a legjobb közös metszet.
