### ISSUE TITLE
API frontend-backend kommunikációját doksiba rögzíteni

### ISSUE THREAD

**Issue by borazslo** [borazslo/koordinaltgyujtes#13]

**Comment by borazslo** [comment]
Szükséges előzmény (ami akár le is fedi ezt): https://github.com/joladnijo/joladnijo-backend/issues/31

**Comment by VFiber** [comment]
Szerintem a Technikai doksi szépen kitér erre is:
https://github.com/joladnijo/joladnijo-docs/blob/main/technikai-dokumentacio/index.md
így ez zárható.
