### ISSUE TITLE
Szerver felajánlást keresünk

### ISSUE THREAD

**Issue by borazslo** [borazslo/koordinaltgyujtes#3]
Git(hub) alapú CI/CD pipeline felépítésére alkalmas php-(my)sql szervert (virtuális gépet) keresünk a projekt működtetéséhez. Lehetőleg skálázhatót.

Más szempont még?
Felajánlások jöhetnek de is.

**Comment by borazslo** [comment]
cpanellel (mysql, állítható php, stb.), sftp hozzáféréssel rugalmas tárhelyet tudunk mi adni, de nincs ssh és root jog, így nem tudom hogy egy jó pipeline könnyen felállítható-e. Cpanelen keresztül egyszerű git(hub) van.

**Comment by edeak** [comment]
AWS? Adomanyokbol fizetheto, vegtelen skalazodik minden komponens.

**Comment by fehergeri13** [comment]
Én firebase-ra szavazok. elején ingyenes, nagyon sok built in dolgot támogat (auth, db stb), nagyon jól skálázódik, pipeline-ra tökéletes (stage, live), és szerintem még a google is szívesen megtámogathatja ha nonprofit a cél.

**Comment by progcode** [comment]
Tudok segiteni VPS-ben, annak konfigjaban es az uzemeltetesben, Digitaloceanon @borazslo 

@fehergeri13 firebase nem kimondottan webhostingra van.

**Comment by fehergeri13** [comment]
> @fehergeri13 firebase nem kimondottan webhostingra van.

Firebase külön támogatja a web appokat specifikusan, ingyenes hostinggal, és csomó mindennel. Szóval ezzel nem értek egyet. De tőlem lehet más a stack. https://firebase.google.com/products/hosting

**Comment by GCsabi** [comment]
ha szeretnénk automatizált teszteket is a folyamatba (ajánlott) akkor azt is érdemes figyelembe venni a pipeline felépítése során. (pl. Robotframework esetén lehessen pythont futtatni) 
Jenkinsünk lesz vagy mi fogja irányítani a folyamatokat?

**Comment by borazslo** [comment]
Végül VPS mellett döntöttünk, és a pipeline amennyire csak lehet a github action-re épül, és lesznek mindenféle tesztek is.

Részletekért csatlakozz a #4 -ben a slack-hez
