### ISSUE TITLE
Adatbázis modellezés tool

### ISSUE THREAD

**Issue by SzilardVigh** [borazslo/koordinaltgyujtes#9]
Sziasztok, ajánlom a [dbdiagram](https://dbdiagram.io/ ) toolt, egy átláthatóbb adatbázis model elkészítéséhez.
Még majd követem a fejleményeket és igyekszem én is segíteni ahol tudok.

**Comment by borazslo** [comment]
Köszi a tippet.

Most ott tartunk, hogy a backend a készülő struktúrából Open Api Json specet készít, főként a modellekre fókuszálva, hogy a frontend-webapp és frontend-backoffice tudja használni. MVP után pedig készítenek belőle npm csomagot és akkor jól verziókövetve lehet mindig a jó és közös formát használni.

Részletekért gyere slack-re. Örömmel várunk.
https://join.slack.com/t/jladnij/shared_invite/zt-14o2v6u1d-E3XUeqiP3IZAmPFIgxLqvw
